# Generated by Django 4.0.2 on 2022-02-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='names')),
                ('last_names', models.CharField(max_length=100, verbose_name='last names')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'crm_customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DUI', 'DUI'), ('NIT', 'NIT'), ('OTHER', 'OTHER'), ('PASSPORT', 'PASSPORT')], default='DUI', max_length=100, verbose_name='document type')),
                ('document', models.CharField(max_length=100, verbose_name='document')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'db_table': 'crm_customer_documents',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK'), ('OTHER', 'OTHER')], default='HOME', max_length=100, verbose_name='address type')),
                ('address', models.TextField(verbose_name='address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'crm_customer_addresses',
            },
        ),
    ]
